events {}

http {
    server {
        listen 80;

        location / {
            # Block SQL Injection patterns
            if ($query_string ~* "('|--|#|or|OR)") {
                return 403;
            }

            proxy_pass http://dvwa;
        }
    }
}
